# Generated by Django 5.1.2 on 2025-11-17 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_created_at_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='achievement_id',
            field=models.CharField(db_column='achievementId', max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='location',
            name='location_id',
            field=models.CharField(db_column='locationId', max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_no',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(db_column='userId', max_length=15, primary_key=True, serialize=False),
        ),
    ]
