# Generated by Django 5.1.2 on 2025-11-17 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_achievement_achievement_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='default_image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
