# Generated by Django 5.1.2 on 2025-11-18 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_user_first_name_user_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='province',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
